FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y python3-pip python3-dev git gcc dos2unix g++

WORKDIR /app

COPY ./requirements_app.txt /app/requirements_app.txt

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements_app.txt

COPY . /app

EXPOSE 5000

CMD ["python3", "app.py"]
